server:
  port: 7070

demo:
  lock:
    # RedisSon分布式锁
    locker-type: redis
  redis:
    enabled: true
    # 开启Key压缩模式
    hash-key-enabled: true
    # 单bucket允许的hashKey数量
    hash-key-count: 30000
    # Redis消息监听器容器
    event-notice: false

spring:
  application:
    name: demo
  aop:
    # 是否基于类的方式代理（cglib），false基于JDK接口的代理将起作用
    proxy-target-class: true
    # 开启AOP，等同于@EnableAspectJAutoProxy
    auto: true
  redis:
    client-name: ${spring.application.name}-Redis
    host: 192.168.0.120
    port: 6379
    password: lMx08!@#1
    database: 0
    timeout: 3000
    # Lettuce 客户端连接池配置
    lettuce:
      pool:
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: 10M
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8